"""Predefined book catalog for bulk import.
Each book: title, author, category, rent_fee, deposit, qty=1
+ optional: publisher, year, cover_type, language, city
categories: badiiy, klassika, psixologiya, tarix, siyosat, ilmiy, biografiya
"""

FULL_CATALOG = [
    {"title": "O'tkan kunlar", "author": "Abdulla Qodiriy", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Yosh gvardiya", "year": 2019, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Mehrobdan chayon", "author": "Abdulla Qodiriy", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "G'afur G'ulom", "year": 2020, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Kecha va kunduz", "author": "Abdulla Qodiriy", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Sharq", "year": 2018, "cover_type": "qattiq", "language": "uz"},
    {"title": "Utgan kunlar", "author": "Abdulla Qodiriy", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Yosh gvardiya", "year": 2017, "cover_type": "yumshoq", "language": "ru"},
    {"title": "Cholpon", "author": "Abdulhamid Cho'lpon", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Sharq", "year": 2019, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Hikoyatlar", "author": "G'afur G'ulom", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Sharq", "year": 2020, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Shum bola", "author": "G'afur G'ulom", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Yosh gvardiya", "year": 2018, "cover_type": "qattiq", "language": "uz"},
    {"title": "Yulduzli tunlar", "author": "Oybek", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Sharq", "year": 2019, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Navoiy", "author": "Oybek", "category": "biografiya", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "G'afur G'ulom", "year": 2017, "cover_type": "qattiq", "language": "uz"},
    {"title": "Qutlug' qon", "author": "Oybek", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Sharq", "year": 2020, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Tong otguncha", "author": "Tohir Malik", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Sharq", "year": 2018, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Shaytanat", "author": "Tohir Malik", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Sharq", "year": 2019, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Jinoyat va jazo", "author": "Fyodor Dostoyevskiy", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Eksmo", "year": 2019, "cover_type": "qattiq", "language": "ru"},
    {"title": "Anna Karenina", "author": "Lev Tolstoy", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "ACT", "year": 2018, "cover_type": "qattiq", "language": "ru"},
    {"title": "Urush va tinchlik", "author": "Lev Tolstoy", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Eksmo", "year": 2017, "cover_type": "qattiq", "language": "ru"},
    {"title": "Ota va bola", "author": "Ivan Turgenev", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "AST", "year": 2019, "cover_type": "yumshoq", "language": "ru"},
    {"title": "Oblomov", "author": "Ivan Goncharov", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Eksmo", "year": 2018, "cover_type": "yumshoq", "language": "ru"},
    {"title": "Jonli murda", "author": "Nikolay Gogol", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "ACT", "year": 2017, "cover_type": "yumshoq", "language": "ru"},
    {"title": "Gertruda", "author": "Hermann Hesse", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "AST", "year": 2019, "cover_type": "yumshoq", "language": "ru"},
    {"title": "Siddxarta", "author": "Hermann Hesse", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Eksmo", "year": 2018, "cover_type": "yumshoq", "language": "ru"},
    {"title": "1984", "author": "George Orwell", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Penguin", "year": 2019, "cover_type": "yumshoq", "language": "en"},
    {"title": "Hayot fermasi", "author": "George Orwell", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Penguin", "year": 2018, "cover_type": "yumshoq", "language": "en"},
    {"title": "O'zimiz va birodar", "author": "George Orwell", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Penguin", "year": 2017, "cover_type": "yumshoq", "language": "en"},
    {"title": "Mag'rur va xunuk", "author": "Jane Austen", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Oxford", "year": 2019, "cover_type": "qattiq", "language": "en"},
    {"title": "Chaqaloq qabul qiluvchilar", "author": "Aldous Huxley", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Vintage", "year": 2018, "cover_type": "yumshoq", "language": "en"},
    {"title": "Ulduzlar ostida", "author": "Ernest Hemingway", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Scribner", "year": 2017, "cover_type": "yumshoq", "language": "en"},
    {"title": "Qartalarga qolgan odam", "author": "Ernest Hemingway", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Scribner", "year": 2019, "cover_type": "yumshoq", "language": "en"},
    {"title": "Kichik shahzoda", "author": "Antoine de Saint-Exupery", "category": "klassika", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Reynal", "year": 2018, "cover_type": "qattiq", "language": "ru"},
    {"title": "Sovuq qon", "author": "Truman Capote", "category": "badiiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Vintage", "year": 2017, "cover_type": "yumshoq", "language": "en"},
    {"title": "Sizni o'ylayapman", "author": "Malcolm Gladwell", "category": "psixologiya", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Little Brown", "year": 2019, "cover_type": "yumshoq", "language": "en"},
    {"title": "Aniq vaqt", "author": "Daniel Kahneman", "category": "psixologiya", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Farrar", "year": 2018, "cover_type": "qattiq", "language": "en"},
    {"title": "Odamning qisqa tarixi", "author": "Yuval Noah Harari", "category": "tarix", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Dvir", "year": 2019, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Sapiens", "author": "Yuval Noah Harari", "category": "tarix", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Harper", "year": 2018, "cover_type": "qattiq", "language": "en"},
    {"title": "Homo Deus", "author": "Yuval Noah Harari", "category": "tarix", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Harper", "year": 2017, "cover_type": "yumshoq", "language": "en"},
    {"title": "O'zbekiston tarixi", "author": "A. Asqarov", "category": "tarix", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "O'zbekiston", "year": 2019, "cover_type": "qattiq", "language": "uz"},
    {"title": "Amir Temur", "author": "R. G'ulomov", "category": "biografiya", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Sharq", "year": 2018, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Temuriylar davri", "author": "B. Akhmadjonov", "category": "tarix", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Fan", "year": 2017, "cover_type": "qattiq", "language": "uz"},
    {"title": "Siyosiy nazariya", "author": "Andrew Heywood", "category": "siyosat", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Palgrave", "year": 2019, "cover_type": "yumshoq", "language": "en"},
    {"title": "Respublika", "author": "Platon", "category": "siyosat", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Penguin", "year": 2017, "cover_type": "yumshoq", "language": "ru"},
    {"title": "O'zbekiston Konstitutsiyasi", "author": "O'zR", "category": "siyosat", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Adolat", "year": 2020, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Qisqa ilm tarixi", "author": "Stephen Hawking", "category": "ilmiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Bantam", "year": 2019, "cover_type": "yumshoq", "language": "en"},
    {"title": "Grand Dizayn", "author": "Stephen Hawking", "category": "ilmiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Bantam", "year": 2018, "cover_type": "qattiq", "language": "en"},
    {"title": "Cosmos", "author": "Carl Sagan", "category": "ilmiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Random House", "year": 2017, "cover_type": "yumshoq", "language": "en"},
    {"title": "Pale Blue Dot", "author": "Carl Sagan", "category": "ilmiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Random House", "year": 2019, "cover_type": "yumshoq", "language": "en"},
    {"title": "Ishonch", "author": "Brené Brown", "category": "psixologiya", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Gotham", "year": 2019, "cover_type": "yumshoq", "language": "en"},
    {"title": "O'ylash tez va sekin", "author": "Daniel Kahneman", "category": "psixologiya", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Farrar", "year": 2018, "cover_type": "qattiq", "language": "uz"},
    {"title": "Zamonaviy psixologiya", "author": "S. Shukurov", "category": "psixologiya", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Universitet", "year": 2019, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Dasturlash asoslari", "author": "A. Karimov", "category": "ilmiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Universitet", "year": 2020, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Python dasturlash", "author": "M. Abdullayev", "category": "ilmiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Fan", "year": 2019, "cover_type": "yumshoq", "language": "uz"},
    {"title": "Ma'lumotlar tuzilmasi", "author": "N. Xolmatov", "category": "ilmiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "Universitet", "year": 2018, "cover_type": "qattiq", "language": "uz"},
    {"title": "Algoritmlar", "author": "T. Cormen", "category": "ilmiy", "rent_fee": 0, "deposit": 0, "qty": 1, "publisher": "MIT Press", "year": 2017, "cover_type": "qattiq", "language": "en"},
]
